Add using on Read The Docs instructions
executablebooks/MyST-Parser pull request #156
Opened 2020-06-03 12:44 UTC by mlncn

This is a start to addressing #155

2020-06-03 15:21 UTC, chrisjsewell requested changes

2020-06-03 15:21 UTC, chrisjsewell commented on docs/using/on_rtd.md
> +- {ref}`The MyST Syntax Guide <using/syntax>`
```suggestion
- [The MyST Syntax Guide](example_syntax)
```

2020-06-03 15:21 UTC, chrisjsewell commented on docs/using/on_rtd.md
> +- {ref}`The MyST Syntax Guide <using/syntax>`
If you didn't know you can also use markdown style links in-place of the sphinx roles like `ref` or `doc` 😄

2020-06-03 15:23 UTC, chrisjsewell commented
Thanks @mlncn some review comments above, also you may want to look at https://myst-parser.readthedocs.io/en/latest/develop/contributing.html#code-style, to ensure that the pre-commit check pass before commiting

2020-06-03 15:25 UTC, choldgraf commented
Thanks for the contribution! Given how common it is for people to use RTD, do you think we could instead append this content as a final section to the getting started page? (https://myst-parser.readthedocs.io/en/latest/using/intro.html)

2020-06-03 15:26 UTC, chrisjsewell commented
Yeh I wouldn't be adverse to that

2020-06-18 18:29 UTC, mlncn commented on docs/using/on_rtd.md
> +```txt
if plain ``` will look OK, then that i think?  If not the `notmuch` email should work.

2020-06-18 18:30 UTC, mlncn commented
Will shift to appending and finally get this wrapped up later tonight!

2020-12-20 11:09 UTC, pradyunsg commented
Hey @mlncn, is there any help you'd need to move this forward, or is the blocker just the number of hours in a day? :)

2020-12-21 18:28 UTC, mlncn commented
@pradyunsg whoops yeah i should not be the blocker on this if you'd be willing to put the documentation updates in the right place!  Thank you!

2021-05-06 08:12 UTC, astrojuanlu commented
Hi folks, I would be happy to move this forward :) If @mincn ran out of stamina, may I open a new pull request with their commits?

2021-05-06 09:16 UTC, chrisjsewell commented
Well I certainly won't stop you 😄

2021-05-06 13:01 UTC, choldgraf commented
@astrojuanlu go for it - happy to review docs PRs 👍

2026-07-12 14:24 UTC, chrisjsewell commented
Closing as part of a triage of the open PR queue — the documentation has been restructured a few times since this was opened, so this no longer applies cleanly. Thanks for the contribution; #155 remains the place to track RTD setup docs if there's still a gap.

2026-07-12 14:25 UTC, closed without merging

2026-07-13 07:37 UTC, astrojuanlu commented
Typical cookie licking @astrojuanlu smh -- oops that's me...